### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by cdalexndr** [alfredosalzillo/rollup-plugin-multi-input#12]
```
[!] SyntaxError: Unexpected token ...
C:\...\node_modules\fast-glob\node_modules\micromatch\index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions..js (C:\...\AppData\Roaming\npm\node_modules\rollup\bin\rollup:1039:17)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\...\node_modules\fast-glob\out\utils\pattern.js:6:20)
```

Config file:
```
import multiInput from 'rollup-plugin-multi-input';
export default {
    input: ['public/**/*.js'],
    output: {
        file: 'bundle.js',
        format: 'iife',
        name: 'bundle'
    },
    plugins: [
        multiInput()
    ]
}
```
rollup v1.16.4

**Comment by alfredosalzillo** [comment]
What is the node version?

**Comment by cdalexndr** [comment]
node v6.5.0

**Comment by alfredosalzillo** [comment]
It's a problem of the library micromatch, used by fast-glob. Micromatch only supports a node version > 8.
Try to update the node version.

**Comment by cdalexndr** [comment]
Updated node to v10.16.0 and the error is gone.
